import React, { useState } from 'react';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogTitle from '@mui/material/DialogTitle';
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';

// complete the code.  
// instructor adds an assignment to a section
// use mui Dialog with assignment fields Title and DueDate
// issue a POST using URL /assignments to add the assignment

const AssignmentAdd = (props) => {

    const [open, setOpen] = useState(false);
    const [editMessage, setEditMessage] = useState('');
    const [asgnmt, setAsgnmt] = useState({
        id: '', title: '', dueDate: '', secId: '', secNo: ''
    });

    const editOpen = () => {
        setOpen(true);
        setEditMessage('');
    };

    const editClose = () => {
        setOpen(false);
        setAsgnmt({
            id: '', title: '', dueDate: '', secId: '', secNo: ''
        });
        setEditMessage('');
    };

    const editChange = (event) => {
        setAsgnmt({ ...asgnmt, [event.target.name]: event.target.value })
    }

    const onSave = () => {
        // Fixme: is changing id allowed since it is primary key (and autogenerated by db?)

        // if (!/^\d+$/.test(asgnmt.id)) {
        //     setEditMessage("Id must be a positive integer");
        // } else

        if (asgnmt.title === '') {
            setEditMessage("Title can not be blank");
        } else if (!/^\d{4}-\d{2}-\d{2}$/.test(asgnmt.dueDate)) {
            // FIXME: need to also check that the date is not in the future
            setEditMessage("Date format must be YYYY-MM-DD");
        } else if (!/^\d+$/.test(asgnmt.secId)) {
            setEditMessage("Section Id must be a positive integer");
        } else if (!/^\d+$/.test(asgnmt.secNo)) {
            setEditMessage("Section No must be a positive integer");
        } else {
            props.save(asgnmt);
            editClose();
        }
    }

    return (
        <>
            <Button onClick={editOpen}>Add Assignment</Button>
            <Dialog open={open} >
                <DialogTitle>Add Assignment</DialogTitle>
                <DialogContent style={{ paddingTop: 20 }} >
                    <h4>{editMessage}</h4>
                    {/* // FIXME:
                        // Is Assignt Id autogenerated by db?
                    <TextField style={{ padding: 10 }} 
                                autoFocus
                                fullWidth
                                label="Assignment Id"
                                name="asgnmtId"
                                value={asgnmt.id}
                                onChange={editChange} /> */}
                    <TextField style={{ padding: 10 }}
                        fullWidth
                        label="Title"
                        name="title"
                        value={asgnmt.title}
                        onChange={editChange} />
                    <TextField style={{ padding: 10 }}
                        fullWidth
                        label="Due Date"
                        name="dueDate"
                        value={asgnmt.dueDate}
                        onChange={editChange} />
                    <TextField style={{ padding: 10 }}
                        fullWidth
                        label="Section Id"
                        name="secId"
                        value={asgnmt.secId}
                        onChange={editChange} />
                    <TextField style={{ padding: 10 }}
                        fullWidth
                        label="Section Number"
                        name="secNo"
                        value={asgnmt.secNo}
                        onChange={editChange} />
                </DialogContent>
                <DialogActions>
                    <Button color="secondary" onClick={editClose}>Close</Button>
                    <Button color="primary" onClick={onSave}>Save</Button>
                </DialogActions>
            </Dialog>
        </>
    )
}

export default AssignmentAdd;
